[build]
  publish = "dist"
  functions = "netlify/functions"

# Redirigir todas las rutas a index.html para soportar React Router / Expo Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200